name: BLUESKY
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - plotly
  - dash
  - matplotlib
  - beautifulsoup4
  - requests
  - lxml
  - scipy
  - pytest

  # linting
  - black
  - flake8
  - isort
